name: portfolio-performance

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: run python and generate prompt
        id: generate_prompt
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          MARKETAUX_API_KEY: ${{ secrets.MARKETAUX_API_KEY }}
        run: |
          python prep_prompt_action.py
          echo "PROMPT_OUTPUT<<EOM" >> $GITHUB_ENV
          # Append the entire content of prompt.txt to GITHUB_ENV
          # Make sure the delimiter 'EOM' does not appear in your prompt.txt
          cat prompt.txt >> $GITHUB_ENV
          # Write the closing delimiter to GITHUB_ENV
          echo "EOM" >> $GITHUB_ENV

      - name: Run Ollama with prompt
        id: ollama
        uses: ai-action/ollama-action@v1
        with:
          model: llama3.2
          prompt: ${{ env.PROMPT_OUTPUT  }}

      - name: Send email using LLM response
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          MARKETAUX_API_KEY: ${{ secrets.MARKETAUX_API_KEY }}
          FROM_EMAIL: ${{ secrets.FROM_EMAIL }}
          TO_EMAIL: ${{ secrets.TO_EMAIL }}
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
        run: |
          echo "${{ steps.ollama.outputs.response }}" > response.txt
          python prep_email_action.py
